<?php
/**
 * Cart Footer
 * 
 */

?>
<div class="cart-footer">
    <!-- Hard Coded Cart footer -->
    <!-- @todo this hardcoded block could come from a static block so it can be edited by the admin user at any time -->
    <div class="cart-footer__row">
        <div class="cart-footer__col">
            <div class="cart-footer-block cart-footer-block--gradient">
                <h2 class="cart-footer-block__title">Price Promise</h2>
                <p>The promise is simple: if you find what you're looking for, for less, we'll match it.</p>
            </div>
        </div>
        <div class="cart-footer__col">
            <div class="cart-footer-block cart-footer-block--aero-blue">
                <h2 class="cart-footer-block__title">Returns</h2>
                <p>Lorem ipsum text here about returns policey at LogicSpot Shop.</p>
            </div>
        </div>
        <div class="cart-footer__col">
            <div class="cart-footer-contact">
                <p>If you have any questions, please call us on 0800 800 123</p>
            </div>
        </div>
    </div>
    
</div>